<a href="https://colab.research.google.com/github/Avinashvns/numpy-practice/blob/main/NumPy_Practice/array_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Slicing (Sub-array)

Syntax:

      array[start : stop : step]

      start = 0            
      stop = stop -1      position


In [1]:
import numpy as np

a =np.array([10,20,30,40,50])

# first element
print(a[0:8])

# till 3 position
print(a[:3])

# Reverse array
print(a[::-1])

[10 20 30 40 50]
[10 20 30]
[50 40 30 20 10]
