<a href="https://colab.research.google.com/github/Avinashvns/numpy-practice/blob/main/NumPy_Practice/array_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array Indexing

## 1-d Array

In [1]:
import numpy as np
a=np.array([10,20,30,40,50,60])

# Access element
print(a[0])
print(a[3])
print(a[5])

10
40
60


## 2-d Array

In [6]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(b.shape)

# Access single element
print(b[0,0], b[0,2])

# Access column
print(b[:,0])


(3, 3)
1 3
[1 4 7]


# Sub Matrix

In [11]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Row : \n" ,b[0:2])
print("\n Column : \n" ,b[: ,0:2])

Row : 
 [[1 2 3]
 [4 5 6]]

 Column : 
 [[1 2]
 [4 5]
 [7 8]]


## 3-D Array

In [17]:
import numpy as np
c = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

# syntax = (depth,rows,cols)     3d array
print(c.shape)

print("depth 1 : \n " , c[0,:,:])
print("depth 2 : \n" , c[1])


(2, 2, 2)
depth 1 : 
  [[1 2]
 [3 4]]
depth 2 : 
 [[5 6]
 [7 8]]
