<a href="https://colab.research.google.com/github/Avinashvns/numpy-practice/blob/main/NumPy_Practice/boolean_masking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Boolean Masking

    👉 Condition lagao
    👉 True/False ka mask banao
    👉 Sirf wahi values nikalo jo True hain

## 1-D Masking

In [1]:
import numpy as np

a = np.array([10, 25, 30, 5, 60])
mask = a > 20
print(mask)
print(a[mask])

[False  True  True False  True]
[25 30 60]


## Boolean Masking in 2D

In [2]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

mask = b > 50
print(b[mask])

[60 70 80 90]


## Real ML Use Case: Outliers remove

In [3]:
data = np.array([10, 12, 15, 500, 18])
clean = data[data < 100]
print(clean)

[10 12 15 18]


## Row Filtering in 2D

In [10]:
data = np.array([
    [1, 50],
    [2, 80],
    [3, 30],
    [4, 90]
])

# print All score
col_score=data[:,1]
print("All Score : ",col_score)

# Filter rows where score > 60
score_60 = data[data[:,1]>60]
print(score_60)


All Score :  [50 80 30 90]
[[ 2 80]
 [ 4 90]]


# Boolean Masking in 3D

In [13]:
import numpy as np

x = np.array([
    [
        [10, 20],
        [30, 40]
    ],
    [
        [50, 60],
        [70, 80]
    ]
])

print("Shape :",x.shape)

# Condition: values > 50
print(x[x>50])

Shape : (2, 2, 2)
[60 70 80]


## Real Use Case: Image Processing

In [16]:
img = np.array([
    [50, 200],
    [30, 255]
])

bright=img[img > 100]
print(bright)

[200 255]


## Advanced Masking: Replace Values

In [19]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Replace all values > 50 with 0
b[b > 50]=0
print(b)

[[10 20 30]
 [40 50  0]
 [ 0  0  0]]
