<a href="https://colab.research.google.com/github/Avinashvns/numpy-practice/blob/main/NumPy_Practice/Fancy_indexing_np_where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🧠 1. Fancy Indexing kya hota hai?

Fancy indexing me tum directly indices ka list dete ho.

In [2]:
import numpy as np

a=np.array([10,20,30,40,50])

# Select specific elements:

print(a[[0,2,4]])


[10 30 50]


## 🔥 Fancy indexing = COPY (Important)

In [5]:
b=a[[0,2]]
b[0]=999
print(a)

[10 20 30 40 50]


## 🟡 2. Fancy Indexing in 2D

    m[[row_indexes], [col_indexes]]

In [7]:
m = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(m[[0,2]])

# Select specific elements:

print(m[[0,2],[1,2]])

[[10 20 30]
 [70 80 90]]
[20 90]


## 🧠 3. np.where() — ML preprocessing ka king 👑

np.where ka matlab:

👉 condition true ho to ye karo else wo karo

In [8]:
a=np.array([10,25,30,5,60])

result=np.where(a > 20, "High" ,"Low")
print(result)

['Low' 'High' 'High' 'Low' 'High']


## Numeric replacement

In [9]:
b=np.where(a>20 , 1,0)
print(b)

[0 1 1 0 1]


## np.where in 2D Dataset

In [10]:
x=np.array([
    [1, 50],
    [2, 80],
    [3, 30],
    [4, 90]
])

# Replace low scores with 0
x[:,1] = np.where(x[:,1] < 60, 0, x[:,1])
print(x)

[[ 1  0]
 [ 2 80]
 [ 3  0]
 [ 4 90]]
